"""init schema

Revision ID: 8a7f1837ef02
Revises: 
Create Date: 2026-08-02 07:49:01.575223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7f1837ef02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('class_slug', sa.String(length=64), nullable=False),
    sa.Column('rarity_slug', sa.String(length=64), nullable=False),
    sa.Column('card_type', sa.String(length=64), nullable=False),
    sa.Column('set_slug', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('collectible', sa.Boolean(), nullable=False),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('is_wild', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_class_slug'), ['class_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_cost'), ['cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_is_standard'), ['is_standard'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_is_wild'), ['is_wild'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_rarity_slug'), ['rarity_slug'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('class_slug', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decks_user_id'), ['user_id'], unique=False)

    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_threads_deck_id'), ['deck_id'], unique=True)

    op.create_table('deck_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'card_id', name='uq_deck_card')
    )
    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_cards_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deck_cards_deck_id'), ['deck_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('patch_applied', sa.Boolean(), nullable=False),
    sa.Column('patch_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_thread_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_cards_deck_id'))
        batch_op.drop_index(batch_op.f('ix_deck_cards_card_id'))

    op.drop_table('deck_cards')
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_threads_deck_id'))

    op.drop_table('chat_threads')
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decks_user_id'))

    op.drop_table('decks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_rarity_slug'))
        batch_op.drop_index(batch_op.f('ix_cards_name'))
        batch_op.drop_index(batch_op.f('ix_cards_is_wild'))
        batch_op.drop_index(batch_op.f('ix_cards_is_standard'))
        batch_op.drop_index(batch_op.f('ix_cards_cost'))
        batch_op.drop_index(batch_op.f('ix_cards_class_slug'))

    op.drop_table('cards')
    # ### end Alembic commands ###
